# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_which_int <- function(vec, x) {
    .Call('_epm_c_which_int', PACKAGE = 'epm', vec, x)
}

c_which_char <- function(vec, x) {
    .Call('_epm_c_which_char', PACKAGE = 'epm', vec, x)
}

intersect_int <- function(vec1, vec2) {
    .Call('_epm_intersect_int', PACKAGE = 'epm', vec1, vec2)
}

setdiff_int <- function(vec1, vec2) {
    .Call('_epm_setdiff_int', PACKAGE = 'epm', vec1, vec2)
}

getComponentA <- function(commI, commJ) {
    .Call('_epm_getComponentA', PACKAGE = 'epm', commI, commJ)
}

getComponentB <- function(commI, commJ) {
    .Call('_epm_getComponentB', PACKAGE = 'epm', commI, commJ)
}

getComponentC <- function(commI, commJ) {
    .Call('_epm_getComponentC', PACKAGE = 'epm', commI, commJ)
}

getLeavesForNodes <- function(phylo) {
    .Call('_epm_getLeavesForNodes', PACKAGE = 'epm', phylo)
}

getRootToTipEdges <- function(phylo) {
    .Call('_epm_getRootToTipEdges', PACKAGE = 'epm', phylo)
}

getMRCA_from_nodeLeaves <- function(nodeLeaves, taxa) {
    .Call('_epm_getMRCA_from_nodeLeaves', PACKAGE = 'epm', nodeLeaves, taxa)
}

FaithPD_branchIndices <- function(a, phylo, nodeLeaves, spEdges, includeRoot = FALSE) {
    .Call('_epm_FaithPD_branchIndices', PACKAGE = 'epm', a, phylo, nodeLeaves, spEdges, includeRoot)
}

meanNNdist <- function(input) {
    .Call('_epm_meanNNdist', PACKAGE = 'epm', input)
}

minNNdist <- function(input) {
    .Call('_epm_minNNdist', PACKAGE = 'epm', input)
}

cellAvg <- function(input, trait, stat) {
    .Call('_epm_cellAvg', PACKAGE = 'epm', input, trait, stat)
}

intersectList <- function(input, vec) {
    .Call('_epm_intersectList', PACKAGE = 'epm', input, vec)
}

phyloBranchRanges <- function(phylo, speciesList, tipEdges) {
    .Call('_epm_phyloBranchRanges', PACKAGE = 'epm', phylo, speciesList, tipEdges)
}

countCells <- function(cellList, vec) {
    .Call('_epm_countCells', PACKAGE = 'epm', cellList, vec)
}

calcPairwiseTaxonomicSorensen <- function(allComm, component) {
    .Call('_epm_calcPairwiseTaxonomicSorensen', PACKAGE = 'epm', allComm, component)
}

uniqueBranchesForSet <- function(a, tipLabels, spEdges) {
    .Call('_epm_uniqueBranchesForSet', PACKAGE = 'epm', a, tipLabels, spEdges)
}

calcPairwisePhylosor <- function(allComm, phylo, component) {
    .Call('_epm_calcPairwisePhylosor', PACKAGE = 'epm', allComm, phylo, component)
}

calcPairwisePhylosor2 <- function(allComm, phylo, component) {
    .Call('_epm_calcPairwisePhylosor2', PACKAGE = 'epm', allComm, phylo, component)
}

